//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PwgTelegramBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class HarvestAuth
    {
        public int UserId { get; set; }
        public string HarvestCode { get; set; }
        public string HarvestToken { get; set; }
        public Nullable<System.DateTime> HarvestTokenExpiration { get; set; }
        public string HarvestRefreshToken { get; set; }
    }
}
